[build]
  command = "yarn build"
  publish = "docs/.vuepress/dist"

[build.environment]
NODE_VERSION = "16"

[[redirects]]
  from = "/install"
  to = "https://raw.githubusercontent.com/BrewBlox/brewblox-ctl/edge/bootstrap-install.sh"
  status = 301
  force = true
