@startuml Dynamic UI Starter
    Entrypoint -> Datastore: Get plugins
    Entrypoint -> CDN: Get plugin code
    Entrypoint -> PluginA: Import
    Entrypoint -> PluginB: Import
    Entrypoint -> Starter: Start([pluginA, pluginB])
    Starter -> Framework: Load
    Starter -> PluginA: Load
    Starter -> PluginB: Load
@enduml