@startuml "Micro services"

title 
    Microservice architecture

    <back:gray>Not yet specified</back>

    <back:lightgreen>External application</back>

    <back:yellow>Brewblox service implementation</back>

end title

cloud GUI
node Gateway #lightgreen
node Supervisor #gray
node DeviceService #yellow
node RabbitMQ #lightgreen
node HistoryService #yellow
node InfluxDB #lightgreen
node EventSourceService #yellow
node ReportingService #yellow

GUI --> Gateway
Gateway --> HistoryService
Gateway --> DeviceService
Gateway --> ReportingService
Gateway --> EventSourceService
Gateway <--> Supervisor

DeviceService "publish / subscribe" -down-> RabbitMQ

ReportingService --> HistoryService

HistoryService "subscribe" --> RabbitMQ
HistoryService --> InfluxDB

EventSourceService "subscribe" --> RabbitMQ

@enduml
