@startuml "Service Components"
[REST]
[SSE]
[InfluxDB]
[Events]

package Services {
    package Controlbox {
        [Datastore]
        [Backend]
        package Blocks
    }

    package Legacy {
    }

    [DataSource]
    [History]
}

Services .up.> REST
DataSource .up.> "publish" SSE
Services .right.> "sub/pub" Events
History ..> "write" InfluxDB

@enduml









