#!/bin/sh
set -e

# One-click web install script for Docker and BrewBlox
# If this script is hosted at eg https://brewblox.com/install
# You can run it with "curl -sSL https://brewblox.com/install | sh"
#
# - Docker will only be installed if it was not yet present
# - Current user will be added to the "docker" group
# - Docker-compose will be installed
# - Project templates will be installed in the user home directory
# - The Compose UI will be scheduled to start on boot
#

command_exists() {
	command -v "$@" > /dev/null 2>&1
}

do_install() {
    echo "Executing BrewBlox install script..."

    if command_exists docker; then
        echo "Docker is already installed, skipping..."
    else
        curl -sSL https://get.docker.com | sh
    fi

    if id -nG "$USER" | grep -qw "docker"; then
        echo "$USER already belongs to the docker group, skipping..."
    else
        sudo usermod -aG docker $USER
    fi

    sudo apt install -y git python python-pip
    sudo pip install docker-compose

    git clone https://github.com/BrewBlox/brewblox-deployment.git
    cp -r brewblox-deployment/templates/* /home/$USER/
    rm -rf brewblox-deployment/

    cd /home/$USER/startup/
    /bin/bash ./configure_service.sh
    cd -

    echo
    echo "Installation finished."
    echo "Please restart your system before use."
    echo
}

do_install
