@startuml "Automation service deployment"

actor User
cloud UI [
    <b>UI

    - Edit templates
    - Start processes
    - Mark tasks as done
]
database Datastore [
    <b>Datastore

    - Store templates
    - Store processes
    - Store tasks
]
node AutomationService [
    <b>automation service

    - Run processes
    - Create / check tasks
    - Check Spark values
    - Edit Spark settings
]
node SparkService [
    <b>Spark service

    - Read controller values
    - Write controller settings
]
node SparkController [
    <b>Spark controller

    - Read sensors
    - Control actuators
]

User --> UI
UI --> AutomationService
UI ..> SparkService
UI --> Datastore
SparkService --> SparkController
AutomationService --> Datastore
AutomationService --> SparkService

@enduml
