@startuml Basic control chain
component PID
component PWM
component Pin as "Actuator Pin"
component SSP as "Setpoint Sensor Pair"
component Sensor as "Temperature Sensor"

Sensor .down.> "input" SSP
SSP .down.> "input" PID
PID -down-> "drives" PWM
PWM -down-> "drives" Pin

@enduml