@startuml Basic control chain
component Sensor as "Temperature Sensor"
component Setpoint
component PID
component PWM
component Digital as "Digital Actuator"
component Pin as "Pin / OneWire channel"

Sensor .down.> "input" Setpoint
Setpoint .down.> "input" PID
PID -down-> "drives" PWM
PWM -down-> "drives" Digital
Digital -down-> "drives" Pin


@enduml