@startuml HERMS
component HLT_PID as "HLT PID"
component BK_PID as "BT PID"
component MT_PID as "MT PID"

component HLT_PWM as "MT PWM"
component BK_PWM as "BK PWM"

component HLT_Digital as "HLT Digital Actuator"
component BK_Digital as "BK Digital Actuator"

component HLT_Pin as "HLT Element Pin"
component BK_Pin as "BK Element Pin"

component HLT_SSP as "HLT Setpoint"
component MT_SSP as "MT Setpoint"
component BK_SSP as "BK Setpoint"
component HLT_Sensor as "HLT Sensor"
component BK_Sensor as "BK Sensor"
component MT_Sensor as "MT Sensor"
component HLT_Driver as "HLT Setpoint Driver"

HLT_Sensor .down.> "input" HLT_SSP
HLT_SSP .down.> "input" HLT_PID
HLT_PID -down-> "drives" HLT_PWM
HLT_PWM -down-> "drives" HLT_Digital
HLT_Digital -down-> "drives" HLT_Pin

MT_Sensor .down.> "input" MT_SSP
MT_SSP .down.> "input" MT_PID
MT_PID -down-> "drives" HLT_Driver
HLT_Driver -left-> "drives" HLT_SSP

BK_Sensor .down.> "input" BK_SSP
BK_SSP .down.> "input" BK_PID
BK_PID -down-> "drives" BK_PWM
BK_PWM -down-> "drives" BK_Digital
BK_Digital -down-> "drives" BK_Pin

@enduml