@startuml Beer Offset Control Chain
component heat_PID as "Heat PID"
component heat_PWM as "Heat PWM Actuator"
component heat_Pin as "Heat Pin"

component cool_PID as "Cool PID"
component cool_PWM as "Cool PWM Actuator"
component cool_Pin as "Cool Pin"

component fridge_SSP as "Fridge Setpoint Sensor Pair"
component fridge_Sensor as "Fridge Sensor"

component Mutex

component beer_PID as "Beer PID" #Cyan
component beer_SSP as "Beer Setpoint Sensor Pair" #Cyan
component beer_Sensor as "Beer Sensor" #Cyan
component beer_Offset as "Fridge Offset Actuator" #Cyan

fridge_Sensor .down.> "input" fridge_SSP
fridge_SSP .down.> "input" heat_PID
fridge_SSP .down.> "input" cool_PID

heat_PID -down-> "drives" heat_PWM
heat_PWM -down-> "drives" heat_Pin
heat_Pin .right.> Mutex

cool_PID -down-> "drives" cool_PWM
cool_PWM -down-> "drives" cool_Pin
cool_Pin .left.> Mutex

beer_Sensor .down.> "input" beer_SSP
beer_SSP .down.> "input" beer_PID
beer_SSP .down.> "reference" beer_Offset
beer_PID -down-> beer_Offset
beer_Offset -left-> "drives" fridge_SSP

@enduml