@startuml OneWire control chain
component PID
component PWM
component Actuator as "Digital Actuator"
component Chip as "DS2413 Chip" #Cyan
component Setpoint
component Sensor as "Temperature Sensor"

Sensor .down.> "input" Setpoint
Setpoint .down.> "input" PID
PID -down-> "drives" PWM
PWM -down-> "drives" Actuator
Actuator -down-> "drives" Chip
@enduml