@startuml Profile control chain
component Sensor as "Temperature Sensor"
component Profile as "Setpoint Profile" #Cyan
component Setpoint
component PID
component PWM
component Digital as "Digital Actuator"
component Pin as "Spark Pin"

Sensor .down.> "input" Setpoint
Profile -down-> "drives" Setpoint
Setpoint .down.> "input" PID
PID -down-> "drives" PWM
PWM -down-> "drives" Digital
Digital -down-> "drives" Pin

@enduml