@startuml Server linked to devices

node Server
node SparkOne as "Spark controller #1" #cyan
node SparkTwo as "Spark controller #2" #cyan
node Tilt as "Tilt hydrometer" #cyan

Server <-right-> SparkOne
Server <-right-> SparkTwo
Server <-right-> Tilt

SparkOne -[hidden]- SparkTwo
SparkTwo -[hidden]- Tilt
@enduml