@startuml Datamodel

interface DataBlock {
    id: string
    type: string
    profiles: number[]
    data: Object
}

interface Block {
    serviceId: string
    isLoading: bool
}

class OneWireTempSensor {
    data: OneWireTempSensorData
}

class SetPointSimple {
    data: SetPointSimpleData
}

class OneWireTempSensorData << (D,orchid) >> {
    value: Unit
    connected: bool
    offset: Unit
    address: string
}

class SetPointSimpleData << (D,orchid) >> {
    setting: Unit
}

Block -up-|> DataBlock
OneWireTempSensor -up-|> Block
OneWireTempSensor ..> OneWireTempSensorData
SetPointSimple -up-|> Block
SetPointSimple ..> SetPointSimpleData

@enduml